### ISSUE TITLE
Not able to view font-awesome icons

### ISSUE THREAD

**Issue by rajesh-tammina** [simonh1000/angular-http-server#1]
Hi guys, I used angular-http-server for my angular2 app while checking my app I observed that whatever the icons that are displaying in my app normally in lite-server deployment are not displayed in angular-http-server deployment. Could you help my in this ?

**Comment by simonh1000** [comment]
Short answer is that I don't know. do you have any code you can share of how you are using code awesome.

**Comment by RobertShires** [comment]
I am running into this as well. It looks to me like the angular-http-server is returning incorrect MIME type for the font files. http-server correctly returns ```Content-Type:font/woff2``` where as angular-http-server returns ```Content-Type:text/html```. 

This seems to only happen with fonts that have a query string attached. 

/vendor/fontawesome/fonts/fontawesome-webfont.woff2?v=4.5.0 returns incorrect content-type header

**Comment by rajesh-tammina** [comment]
Hi Robert,

                Thanks for responding to my query. Do I need to do any changes to make this work for font-awesome also ?

 

Thanks and regards,

     Rajesh kumar

**Comment by simonh1000** [comment]
I have pushed a new version to npm - let me know how you get on

**Comment by rajesh-tammina** [comment]
Thanks Simon. Its working now. Thanks for immediate response.
