### ISSUE TITLE
issue with path with version 1.4.4 - redirecting all files to index.html

### ISSUE THREAD

**Issue by Bazmcl** [simonh1000/angular-http-server#15]
Have been using your http server for a couple of our angular (5) app... and had been working well

app is running inside a docker container
`
FROM node:latest
EXPOSE 8666
RUN npm install -g angular-http-server
...other stuff
WORKDIR /usr/apps/my-app
ENTRYPOINT angular-http-server -p 8666
`

However the latest version (1.4.4) seems to set the working directory to the angular-http-server dir and we get a bunch of warnings like this:
...
Route /usr/local/lib/node_modules/angular-http-server/usr/apps/my-app/main.bundle.js, replacing with index.html

Rolling back to version 1.4.3 (seems to work fine)
 `
RUN npm install -g angular-http-server@1.4.3
`

**Comment by simonh1000** [comment]
Could you try 1.4.5 just published

**Comment by Bazmcl** [comment]
after 3 minutes of exhaustive - and exhausting ;) testing I can confirm this is resolved on 1.4.5

thanks

**Comment by simonh1000** [comment]
Great. If you continue to find the project useful, a star would be welcome.

**Comment by mold** [comment]
I'm still getting this error using 1.4.5:

```sh
C:\Users\dkd_3\Source\GcWebApp-Angular\platforms\browser\www (add-cordova -> origin)
λ npx angular-http-server@1.4.5
npx: installed 1 in 2.532s
Path must be a string. Received undefined
npx: installed 12 in 3.757s
C:\Users\dkd_3\AppData\Roaming\npm-cache\_npx\19892\node_modules\angular-http-server\angular-http-server.js
Info: Path not specified using the working directory.
Listening on 8080
Route app\c\welcome, replacing with index.html
Route app\c\cordova.js, replacing with index.html
Route app\c\runtime.js, replacing with index.html
Route app\c\polyfills.js, replacing with index.html
Route app\c\styles.js, replacing with index.html
Route app\c\vendor.js, replacing with index.html
Route app\c\main.js, replacing with index.html
Route app\c\content\gc-logo-inverted.svg, replacing with index.html
Route app\c\content\favicons\favicon-32x32.png, replacing with index.html
Route app\c\content\favicons\favicon-16x16.png, replacing with index.html
Route app\c\content\favicons\favicon-96x96.png, replacing with index.html
Route app\c\content\favicons\android-icon-192x192.png, replacing with index.html
```

It works when I add a `/` to the script src's in index.html:

Doesn't work:
```<script type="text/javascript" src="runtime.js"></script>
<script type="text/javascript" src="polyfills.js"></script>
<script type="text/javascript" src="styles.js"></script>
<script type="text/javascript" src="vendor.js"></script>
<script type="text/javascript" src="main.js"></script>```

Works:
```<script type="text/javascript" src="/runtime.js"></script>
<script type="text/javascript" src="/polyfills.js"></script>
<script type="text/javascript" src="/styles.js"></script>
<script type="text/javascript" src="/vendor.js"></script>
<script type="text/javascript" src="/main.js"></script>```

but index.html is generated by `ng build` so I don't want to have to change it every time. Also subsequent requests for e.g. my translation jsons fail in the same way.

Any ideas for how to solve this?

**Comment by zdennis** [comment]
@mold, I add the same issue, but then I found that I was building with an incorrect base-href. Once I resolved that everything works just fine.

Not sure if that will also help you.

**Comment by dpraul** [comment]
This issue appears to occur when you pass in an absolute path when running in a non-Windows environment. The filepath sanitization will always strip out the leading `/`, turning it into a relative link, and thus probably not finding the file.
