### ISSUE TITLE
Fails to serve .gltf files

### ISSUE THREAD

**Issue by nirajupadhyay11** [simonh1000/angular-http-server#28]
Hi,

I am trying to use angular-http-server to serve .gltf/.bin files from the /dist folder created by ng build. However, I get the same error as I got when using ng serve that the asset (.gtlf file) is not found. Am I doing something wrong? I thought ng serve did not work because it uses webpack internally and needs to be configured to use .gltf files.

**Comment by simonh1000** [comment]
I don't think this library does any filtering of files by extension, so I suspect the problem lies elsewhere

**Comment by nirajupadhyay11** [comment]
Okay, I have double checked to make sure the path is correct. You can close this thread if this is not an appropriate forum to discuss this issue. I have raised it on stackoverflow here - https://stackoverflow.com/questions/55095640/webpack-not-serving-files-with-extension-gtlf-bin-in-angular-cli-7
