### ISSUE TITLE
Server index.html in subfolders

### ISSUE THREAD

**Issue by spock123** [simonh1000/angular-http-server#34]
I'm trying to serve a multi language application using angular-http-server.

However I've run into an issue, because it appears the server only serves index.html automatically in the root folder.

So if my app is localized with two languages and organized like this:

```
/
  index.html
   fr
      index.html
   en
      index.html
```

- I cannot serve  the /fr or /en urls, because angular-http-server does not look for index.html in those folders, only the root folder. Would love a change making it possible to look for index.html in the path of the http request.

Thanks

**Comment by dpraul** [comment]
you can do this! just use the `--path` flag:
```sh
angular-http-server --path fr
```

**Comment by spock123** [comment]
Hi @dpraul 

Unfortunately that means I cannot serve the other language folders

**Comment by simonh1000** [comment]
I'm sorry, but this is described as a "simple dev-server" and so your use case is not going to be handled
