### ISSUE TITLE
Support to host config, to enable open in this host

### ISSUE THREAD

**Issue by jpwerka** [simonh1000/angular-http-server#60]
I would like to have the option of supporting the _host_ property, so if I don't want to open the browser on _localhost_, but on another host configured in my _hosts_ file, for example, it would be possible, as the same way that the `ng serve` command supports

```javascript
function start() {
    server.listen(port, function () {
        if (argv.open == true || argv.o) {
            // open a browser tab
            opn((useHttps ? "https" : "http") + ( argv.host ? ("://" + argv.host + ":") : "://localhost:") + port);
        }
        return console.log("Listening on " + port);
    });
}
```

**Comment by simonh1000** [comment]
that would be ok. update the docs as well and you do not need to repeat the `://`
